### ISSUE TITLE
Test failes: Unable to open SPI device: No such file or directory

### ISSUE THREAD

**Issue by gflohr** [stevieb9/rpi-digipot-mcp4xxxx#1]
I ran into this problem, when I wanted to install RPi::WiringPi.

The test init.t fails on my Raspberry Pi 2 Model B Version 1.1.  The OS is Raspbian from 01/2017, WiringPi is installed and working.

Makefile.PL complains about an unparsable version of WiringPi::API although the dependency is installed.  Otherwise I did not notice any errors.

root@raspberrypi:~/RPi-DigiPot-MCP4XXXX-2.36.1# perl -MWiringPi::API -e exit
root@raspberrypi:~/RPi-DigiPot-MCP4XXXX-2.36.1# perl Makefile.PL 
Unparsable version '$' for prerequisite WiringPi::API at Makefile.PL line 6.
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for RPi::DigiPot::MCP4XXXX
Writing MYMETA.yml and MYMETA.json
root@raspberrypi:~/RPi-DigiPot-MCP4XXXX-2.36.1# make test
cp lib/RPi/DigiPot/MCP4XXXX.pm blib/lib/RPi/DigiPot/MCP4XXXX.pm
PERL_DL_NONLAZY=1 PERL_USE_UNSAFE_INC=1 /usr/bin/perl "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-load.t ....... 1/? # Testing RPi::DigiPot::MCP4XXXX 2.36.1, Perl 5.020002, /usr/bin/perl
t/00-load.t ....... ok   
t/boilerplate.t ... ok   
t/bytes.t ......... ok   
t/init.t .......... 1/? Unable to open SPI device: No such file or directory
t/init.t .......... Dubious, test returned 1 (wstat 256, 0x100)
All 9 subtests passed 
t/manifest.t ...... skipped: Author tests not required for installation
t/pod-coverage.t .. skipped: Test::Pod::Coverage 1.08 required for testing POD coverage
t/pod.t ........... skipped: Test::Pod 1.22 required for testing POD

Test Summary Report
-------------------
t/boilerplate.t (Wstat: 0 Tests: 3 Failed: 0)
  TODO passed:   1-3
t/init.t        (Wstat: 256 Tests: 9 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
Files=7, Tests=19,  2 wallclock secs ( 0.25 usr  0.07 sys +  1.32 cusr  0.13 csys =  1.77 CPU)
Result: FAIL
Failed 1/7 test programs. 0/19 subtests failed.
Makefile:838: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255

**Comment by stevieb9** [comment]
Thanks for the report! I'll do some testing and cleanup this evening.

**Comment by stevieb9** [comment]
I've corrected both issues. The first is because you must have an `ExtUtils::MakeMaker` < v6.72, so I've quoted the prerequisite versions that have multiple decimal points, and to further, bumped the prereq version of EUMM to 6.72 minimum.

I'll head on over to the other modules required by `RPi::WiringPi`, and that distribution itself and look to see if any of those would exhibit the same issue.

As far as the init test, I've just disabled it unless `PI_BOARD` environment variable is set to a true value. Essentially, it'll be bypassed. I'll look further into why it was failing on a few of my Pis tonight, as it appears you are on one as well.

Look for v2.36.2 on the CPAN shortly.
